{{- define "lib-hoy.serviceaccount.tpl" -}}
{{ $name := required "'name' must be provided" .name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ $name }}"
{{- end -}}

{{- define "lib-hoy.serviceaccount" -}}
{{ $name := required "'name' must be provided" .name }}
{{ $subsystem := required "'name' must be set in Values.subsystem" $.Values.subsystem.name }}
{{- include "lib-hoy.util.merge" (
    list
        .
        (printf "%s.%s-serviceaccount.merge" $subsystem $name)
        "lib-hoy.serviceaccount.tpl"
    ) -}}
{{- end -}}
