name: Release Charts
permissions:
  contents: write

on:
  push:
    tags:
      - "*" 

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package helm
        run: |
          VERSION=${{ github.ref_name }}
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package \
            charts/lib-hoy \
            --app-version=${VERSION:1} \
            --version=${VERSION:1} \
            --destination=.cr-release-packages \

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
